Feature: frontend
aidagalimova/hacker-news-client pull request #1
Opened 2024-07-29 09:45 UTC by aidagalimova

2024-07-29 16:30 UTC, kseniakap approved these changes

2024-07-29 16:30 UTC, kseniakap commented on src/features/comments/index.tsx
> +const refreshInterfal = 60000;
В проекте ты используешь эту переменную несколько раз, может есть смысл вынести ее в отдельный файл и импортировать? 
export const refreshInterfal = 60000;

2024-07-29 16:30 UTC, kseniakap commented on src/features/comments/index.tsx
> +    return null;
Думаю, пользователя стоит информировать, если что-то пойдет не так

2024-07-29 16:30 UTC, kseniakap commented on src/entities/comments/ui/CommentsItem.tsx
> +      <UserName>{comment.user}</UserName>
user не всегда существует, сделай проверку, если нет 'unknown', я тоже забыла этот момент

2024-07-29 16:30 UTC, kseniakap commented on src/entities/comments/model/services/commentSlice.ts
> +    getCommentsById: builder.query<Comments, string>({
Я писала Александру на счет этого момента, продублирую:
"По заданию было сказано "Корневые комментарии подгружаются сразу же при входе на страницу, вложенные - по клику на корневой", но получается так что загружаются все данные: как корневые так и вложенные комментарии.
Я думаю, требовалось реализовать логику так, чтобы ТОЛЬКО при нажатии на любой из корневых корневых комментариев запрос отправлялся на бэк, а он в свою очередь отдавал данные вложенных комментариев"
Поправьте меня, может я неверно поняла задание (

2024-07-30 10:24 UTC, aidagalimova commented on src/entities/comments/ui/CommentsItem.tsx
> +      <UserName>{comment.user}</UserName>
изменила на бэке

2024-07-30 11:38 UTC, aidagalimova commented on src/entities/comments/model/services/commentSlice.ts
> +    getCommentsById: builder.query<Comments, string>({
Т.к. api возвращает все комментарии целиком, я решила, что "подгрузка" только про отображение на странице

2024-07-31 06:25 UTC, al-revenko requested changes
Сайт не адаптирован под широкие экраны, элементы растягиваются на весь экран без каких либо ограничений. Добавь/модифицируй контейнер чтобы он ограничивал макс ширину своих элементов (max-width: 1440px/1920px/etc...)

При первом запуске выпала такая крокозябра на домашней странице:

![404](https://github.com/user-attachments/assets/4865366c-7498-4442-9d30-aa0d65448875)

У меня был занят 4000 порт, который использует сервер и возможно в этом дело. В дальнейшем  воспроизвести эту ошибку я не смог. Но всё-таки не помешало бы обработать такие случаи

\+  нет сообщения когда произошла ошибка при получении данных

![404 alt](https://github.com/user-attachments/assets/2a25a017-f4ac-4e3f-b4e7-a6aa4c172c98)

2024-07-31 06:25 UTC, al-revenko commented on public/index.html
> +</html>
Отредактируй шаблон. Удали комментарии, измени title

2024-07-31 06:25 UTC, al-revenko commented on src/app/theme/breakpoints.ts
> +};
Больше придирка, а не замечание. Можешь не исправлять

Breakpoints выглядит как константа и наверное лучше добавить `as const `, чтобы проперти объекта были доступны только для чтения, и перенести её в папку const к другим константам.

Я понимаю почему брейкпоинты лежат в папке темы - потому что они используются только в ней, но, чисто гипотетически, может появиться потребность использовать значения из этого объекта в функциях по типу useMediaQuery, когда нужно программно указать брейкпоинт. Поэтому, наверное, лучше будет если эти значения не будут замыкаться только на теме

2024-07-31 06:25 UTC, al-revenko commented on src/entities/comments/ui/CommentsItem.tsx
> +  const ReqursiveComments = () => {
опечатка - recursive

2024-07-31 06:25 UTC, al-revenko commented on src/entities/comments/ui/CommentsItem.tsx
> +  const isHaveComments = comment.comments.length !== 0;
Можно просто comment.comments.length > 0

2024-07-31 06:25 UTC, al-revenko commented on src/entities/comments/ui/CommentsItem.tsx
> +        ))}
Наверное лучше будет переиспользовать компонент списка

По сути это `<CommentsList comments={comment.comments} />` отличие только в isChild, но его можно сделать необязательным булевым пропом:  `<CommentsList comments={comment.comments} isChild />`

2024-07-31 06:25 UTC, al-revenko commented on src/entities/news/ui/NewsItem.tsx
> +    <Container onClick={() => navigate(`${news.id}`)}>
Лучше сделать ссылкой (компонентом `<Link />` от react-router-dom, например).

Вообще старайся такие вещи делать именно ссылкой, а не кнопкой:
https://confluence.web-bee.ru/display/DEVELOPER/Developer+-+Bad+practices

2024-07-31 06:25 UTC, al-revenko commented on src/features/allNews/index.tsx
> +        <Refresh handleClick={handleRefetch} />
Кнопку лучше блокировать когда идёт запрос

2024-07-31 06:25 UTC, al-revenko commented on src/features/comments/index.tsx
> +        <Refresh handleClick={handleRefetch} size={IconSize.Small} />
Тут тоже лучше проставить блокировку кнопки во время запроса

2024-07-31 06:25 UTC, al-revenko commented on src/widgets/PopUp/index.tsx
> +const hideTime = 1000;
А зачем это нужно? Я так понимаю popup скрывается через это время? Наверное лучше скрывать его по булевому условию (isShow пропс, например)

2024-07-31 08:46 UTC, G00syara commented on src/entities/comments/ui/CommentsItem.tsx
> +  const isHaveComments = comment.comments.length !== 0;
Можно ещё короче !!comment.comments.length

2024-07-31 09:39 UTC, aidagalimova commented on src/widgets/PopUp/index.tsx
> +const hideTime = 1000;
Сделала скрытие попапа через секунду, чтобы пользователь успел увидеть, что его клик на перезагрузку сработал

2024-07-31 09:40 UTC, aidagalimova commented
> И небольшая придирка. Это не надо исправлять, наверное это вообще не стоит того, но у тебя немного перемешанная структура проекта. Компоненты соседствуют с моделями, компоненты находятся на одном уровне с папкой shared где есть всевозможные приколы не относящиеся напрямую к компонентам и т.д. Это наглядно видно на примере папок app и entities. Лучше было бы если все компоненты лежали в папке components а все модели, ассеты, сервисы и т.д лежали в отдельных своих папках. Не критично, но немного сложно ориентироваться

Пыталась делать по Feature-Sliced Design https://feature-sliced.design/ru/docs/get-started/overview

2024-08-01 08:21 UTC, al-revenko requested changes
Ограничение ширины есть у основного контента, однако у хедера её нет, а должна быть \+ контент не центрирован и получается так что он прилипает к левому краю.

![max-width](https://github.com/user-attachments/assets/ad83cae5-2274-4fde-9863-ecab17fd185e)

Я думаю что делать ограничение ширины на уровне `<PageContainer />`
не очень хорошая идея так как это сложнее переиспользовать (ограничение ширины нужно и хедеру, но он за пределами `<PageContainer />`

Лучше будет сделать отдельный div компонент, который будет ограничивать и центрировать себя по отношению к странице. И потом просто пихать его в компоненты где нужно ограничение

Вот как я сделал: https://github.com/al-revenko/hacker-news-front/blob/feature/src/components/layouts/ContentLayout.tsx

Там используется mui container, но по сути это
```css
div {
height: 100%; /* не обязательно  */
max-width: 1440px; /* ограничивает ширину  */
margin: 0 auto; /* центрирует контейнер когда ширина > 1440px*/
}
```

2024-08-01 12:24 UTC, al-revenko approved these changes

2024-08-01 19:46 UTC, G00syara commented
Мне нравится вёрстка, сделано классно!!!

2024-08-01 19:47 UTC, G00syara commented
А теперь по замечаниям.
Не критично, но попробуй сделать так, чтобы когда ты открыла комментарии например до 4 уровня вложенности, потом скрыла с самого верхнего уровня и открыла заново, у тебя все ранее открытые комментарии должны быть открыты. Сейчас они скрыты и их приходится заново открывать. Если не совсем поняла о чем я, могу показать в войсе

2024-08-01 19:47 UTC, G00syara commented
Сделай имитация загрузки дочерних комментариев при их первом открытий, если комментарий скрыли и заново открыли, загрузки не должно быть, т.к. фактически ты уже её загрузила

2024-08-01 19:54 UTC, G00syara commented
Мне кажется лучше в кол-ве комментариев писать количество всех дочерних комментариев, а не только на первом уровне вложенности, т.е. если у тебя на 1 уровне вложенности 4 комментария, на 2 уровне 6 комментариев и на 3 уровне 1 комментарий, то должно отображать 11 комментариев, а не 4

2024-08-01 20:39 UTC, G00syara commented
Кнопка обновления при нажатии на странице новости, не корректно отображает спинер. Странно, что на главной странице он у тебя нормально работает, а на странице новости, анимация сбрасывается при нажатии

2024-08-01 20:41 UTC, G00syara requested changes

2024-08-01 20:41 UTC, G00syara commented on .env.local
Обычно этот файл называют .env.example

2024-08-01 20:41 UTC, G00syara commented on src/app/router/index.tsx
> +const router = createBrowserRouter([
Сделай страницу с 404 ошибкой. Если человек введёт не тот id новости, чтобы оно открывало её

2024-08-01 20:41 UTC, G00syara commented on src/app/store/index.ts
> +  ui: uiReducer,
Не совсем понял, зачем тут `ui` можешь объяснить?

2024-08-01 20:41 UTC, G00syara commented on src/entities/comments/model/types/commentType.ts
> +  comments_count: number;
`pascalCase`, если проблема на 10 строке, то назови как нибудь по другому

2024-08-01 20:41 UTC, G00syara commented on src/entities/news/model/services/newsSlice.ts
> +    getAllNews: builder.query<NewsType[], void>({
Почему `void`? Тут же и `undefined` подходит, `void` используется в функция обозначая, что он возвращает пустоту, т.е. ничего

2024-08-01 20:41 UTC, G00syara commented on src/features/allNews/index.tsx
> +  } = newsApi.useGetAllNewsQuery(undefined, { pollingInterval: refreshInterfal });
Как будто бы странно, что тебе нужно прокидывать `undefined`, чтобы получить все новости, попробуй это исправить

2024-08-01 20:41 UTC, G00syara commented on src/features/allNews/index.tsx
> +  const dispatch = useDispatch();
Также попробуй типизировать `dispatch`, это делается в папке с объявлением middleware

2024-08-01 20:41 UTC, G00syara commented on src/features/comments/index.tsx
> +      <ErrorContainer>
Можешь вынести сообщение об ошибке в компонент и вызывать его в тех местах, где произошла ошибка

2024-08-02 09:17 UTC, aidagalimova commented on src/entities/news/model/services/newsSlice.ts
> +    getAllNews: builder.query<NewsType[], void>({
В документации сказано использовать void
>  When used with TypeScript, you should supply generics for the return type and the expected query argument: build.query<ReturnType, ArgType>. If there is no argument, use void for the arg type instead.

![изображение](https://github.com/user-attachments/assets/0a651bb2-9884-4cb3-8364-b0b2e967b284)

2024-08-02 12:13 UTC, aidagalimova commented on src/app/store/index.ts
> +  ui: uiReducer,
Только для `PopUp`,
`PopUp` должен появляться при перезагрузке списков и поэтому иначе пришлось бы его состояние `isDisplay` и логику скрытия, вынести в компоненты, в которых этот `PopUp` используется. 

Назвала ui для масштабируемости

2024-08-02 12:37 UTC, aidagalimova commented on src/features/allNews/index.tsx
> +  } = newsApi.useGetAllNewsQuery(undefined, { pollingInterval: refreshInterfal });
Да, но хук `useGetAllNewsQuery` генерируется `RTK query`, и первым параметром всегда ожидает `queryArg`, а параметров у данного запроса нет

Не придумала как исправить, в доках решения тоже не нашла..

2024-08-02 17:21 UTC, aidagalimova commented
> Мне кажется лучше в кол-ве комментариев писать количество всех дочерних комментариев, а не только на первом уровне вложенности, т.е. если у тебя на 1 уровне вложенности 4 комментария, на 2 уровне 6 комментариев и на 3 уровне 1 комментарий, то должно отображать 11 комментариев, а не 4

Чтобы корректно заработало, надо бэк запулить

2024-08-05 13:07 UTC, G00syara commented on src/app/store/index.ts
> +  ui: uiReducer,
Пообщался с Сергеем, есть предложение переименовать ui, на uiState, потому что это у тебя не весь ui, а просто кусок ui, с его состоянием

2024-08-06 14:15 UTC, G00syara commented on src/features/allNews/index.tsx
> +  } = newsApi.useGetAllNewsQuery(undefined, { pollingInterval: refreshInterfal });
Хм... поищу как можно было бы исправить пока оставь так

2024-08-06 14:21 UTC, G00syara commented on src/features/allNews/index.tsx
> +      {news && <NewsList news={news} />}
Лучше выводить, что то одно, потому что если вдруг будет так, что у тебя загрузились новости и почему ты пришла ошибка, то выведется ошибка, а не данные.
В других местах аналогично, можно сделать компонент, в который ты будешь значения пропами прокидывать

2024-08-06 18:19 UTC, sspopkov requested changes

2024-08-06 18:19 UTC, sspopkov commented on src/features/allNews/index.tsx
> +  } = newsApi.useGetAllNewsQuery(undefined, { pollingInterval: refreshInterfal });
Передавай просто пустой объект `{}` вместо undefined

2024-08-06 18:19 UTC, sspopkov commented on src/entities/comments/ui/CommentsItem.tsx
> +  const isHaveComments = !!comment.comments.length;
Название не совсем на английском, лучше `hasComments`

2024-08-06 18:19 UTC, sspopkov commented on src/entities/comments/ui/CommentsItem.tsx
> +        <CommentContent dangerouslySetInnerHTML={{ __html: comment.content }}></CommentContent>
Используй здесь DOMPurify, так как это потенциально опасный код

2024-08-06 18:19 UTC, sspopkov commented on src/entities/comments/ui/CommentsList.tsx
> +export const CommentsList = ({ comments, isChild }: CommentsProps) => {
Для isChild лучше значение по умолчанию указать

2024-08-06 18:19 UTC, sspopkov commented on src/entities/news/ui/News.tsx
> +const User = styled.div`
Для названий используем `span`

2024-08-06 18:19 UTC, sspopkov commented on src/entities/news/ui/NewsItem.tsx
> +const Title = styled.span`
Для заголовков правильнее использовать `h1`, `h2`, `h3`

2024-08-06 18:19 UTC, sspopkov commented on src/shared/ui/Refresh/index.tsx
> +    <Spin onClick={handleClick} className={`${size ? size : ''}`} disabled={isFetching}>
Почему не просто `size={size}`?

2024-08-06 18:19 UTC, sspopkov commented on src/shared/ui/Refresh/index.tsx
> +export const Refresh = ({ isFetching, size, handleClick }: RefreshProps) => {
И здесь по умолчанию `size = IconSize.Middle` какой-нибудь указать просто

2024-08-06 18:19 UTC, sspopkov commented on src/shared/uiSlice/index.ts
> +interface uiSchema {
Интерфейсы именуем в PascalCase

2024-08-06 19:19 UTC, aidagalimova commented on src/shared/ui/Refresh/index.tsx
> +    <Spin onClick={handleClick} className={`${size ? size : ''}`} disabled={isFetching}>
На лекции вроде говорили, что использование классов более оптимизировано

2024-08-06 19:21 UTC, aidagalimova commented on src/features/allNews/index.tsx
> +      {news && <NewsList news={news} />}
не очень поняла про
> сделать компонент, в который ты будешь значения пропами прокидывать

2024-08-06 20:02 UTC, sspopkov commented on src/shared/ui/Refresh/index.tsx
> +    <Spin onClick={handleClick} className={`${size ? size : ''}`} disabled={isFetching}>
Это так, но здесь неоправданно усложнять дополнительным классом

2025-02-03 13:18 UTC, merged